title: The Back Room
description: Open-Source Development and Graphic Design

favicon_ico: "/assets/icon.ico"
logo: "/assets/logo.png"

remote_theme: just-the-docs/just-the-docs
color_scheme: dark
callouts:
  warning:
    title: Warning
    color: red

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

mermaid:
  version: "9.1.3"

heading_anchors: true
nav_enabled: true
search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
  focus_shortcut_key: 'k'

pages:
- 404.md
- index.md
- themes.md
- themes/rtm.md
- themes/regional.md
- themes/other.md
- themes/ultimate.md
- themes/box-art.md

nav_external_links:
- title: Back
  url: https://the-back-room.github.io/
  hide_json: false
  open_in_new_tab: false
